version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecret123
      - ALLOWED_HOSTS=ec2-18-209-51-193.compute-1.amazonaws.com

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:8080"
    depends_on:
      - app

volumes:
  static_data:

# To run this on prod: docker-compose -f docker-compose-deploy.yml up --build